version: '3'
services:
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
    - ${NGIX_PORT}:${NGIX_PORT}
    networks:
    - main_network
    volumes:
    - ./nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
    - back

  back:
    build: .
    container_name: "dataset"
    command: python -m tornado.autoreload main.py
    volumes:
    - .:/app
    ports:
    - ${API_PORT}:${API_PORT}
    networks:
    - main_network

networks:
  main_network:
    driver: bridge

